# 9. Numpy

In [1]:
import numpy as np
n,m=200,500
# generating matrix A
A = np.random.normal(0, 1, (n, m))

# generating matrix B(Toeplitz)
tmp = np.random.rand(m)
B = np.zeros((np.size(tmp),np.size(tmp)))

B[0,:],B[:,0] = tmp,tmp
for i in range(1,np.size(tmp)):
    for j in range(1,np.size(tmp)):
        B[i,j] = B[i-1,j-1]
A,B

(array([[ 0.76446337,  0.97514338,  1.34238002, ...,  0.95804246,
         -0.93159189, -1.45221944],
        [-0.42696789,  1.3117067 , -0.8833006 , ..., -0.60051616,
         -0.05790041,  0.77592841],
        [ 1.71600717,  0.26038116,  0.93356727, ..., -0.3495187 ,
          0.52720237, -0.15065565],
        ...,
        [-0.37736526, -1.41035934,  0.35572938, ...,  1.76295103,
          0.56276245,  0.87526249],
        [ 0.13809786,  0.45969546,  1.1445652 , ...,  0.04304327,
          0.3754865 ,  0.80602898],
        [ 1.45393802,  0.85434545,  0.54746806, ..., -0.21693128,
         -0.62608542,  0.65777537]]),
 array([[0.01818061, 0.80177257, 0.82357442, ..., 0.98933081, 0.22473623,
         0.91116021],
        [0.80177257, 0.01818061, 0.80177257, ..., 0.92812283, 0.98933081,
         0.22473623],
        [0.82357442, 0.80177257, 0.01818061, ..., 0.26368451, 0.92812283,
         0.98933081],
        ...,
        [0.98933081, 0.92812283, 0.26368451, ..., 0.01818061, 0.80177257

## 9.1. Matrix operations

In [2]:
q1= A+A
q2= A@A.transpose()
q3= A.transpose()@A
q4= A@B
print(q1,q2,q3,q4)

def compute(A,B,lambda1):
    return A@(B-lambda1 * np.eye(m, m))
print("----------------------------------------\n",compute(A,B,3))

[[ 1.52892673  1.95028676  2.68476004 ...  1.91608492 -1.86318377
  -2.90443887]
 [-0.85393579  2.62341339 -1.76660119 ... -1.20103232 -0.11580081
   1.55185682]
 [ 3.43201435  0.52076231  1.86713453 ... -0.6990374   1.05440474
  -0.3013113 ]
 ...
 [-0.75473053 -2.82071868  0.71145877 ...  3.52590206  1.12552489
   1.75052498]
 [ 0.27619573  0.91939092  2.28913041 ...  0.08608655  0.75097299
   1.61205797]
 [ 2.90787604  1.70869089  1.09493612 ... -0.43386257 -1.25217084
   1.31555074]] [[ 5.06353390e+02 -2.77098670e+01  2.88357291e+01 ... -4.51695598e-01
   4.01797753e+01 -2.75997911e+01]
 [-2.77098670e+01  5.14817736e+02 -1.12412241e+01 ...  1.61792859e+01
   2.74333002e+01  3.35114571e+01]
 [ 2.88357291e+01 -1.12412241e+01  4.47946639e+02 ... -4.24153882e+01
   6.59904497e+00 -5.37436696e+00]
 ...
 [-4.51695598e-01  1.61792859e+01 -4.24153882e+01 ...  5.22640489e+02
   1.08986617e+01 -1.35478957e+01]
 [ 4.01797753e+01  2.74333002e+01  6.59904497e+00 ...  1.08986617e+01
   5.08245110

## 9.2. Solving a linear system

In [3]:
# Bx= b
b = np.random.rand(m)
x = np.linalg.solve(B, np.transpose(b))
x

array([-7.07668965e-02,  5.62299961e-01,  1.52439426e+00, -9.19407254e-01,
        2.76671543e+00, -1.56599492e+00,  8.98148299e-02, -3.78225375e-01,
       -1.55355901e-01, -4.04660051e-01,  1.38274997e+00, -1.60339752e+00,
        2.32862191e-01, -9.56951412e-01, -7.83918103e-01,  2.16394347e+00,
       -1.41037695e-03,  5.53113103e-01,  1.49530688e+00, -1.07273734e+00,
        1.70094977e-01, -4.17509698e-01,  4.49295150e-01,  1.17684030e+00,
       -1.51241541e+00,  2.30763805e+00, -1.54609220e+00, -9.09610764e-01,
        1.99153833e-01,  1.78958627e-01, -8.38627955e-01,  2.72806960e+00,
       -8.88833671e-01, -9.69946963e-01,  3.93815562e-01, -1.73472006e+00,
        7.26525920e-01,  6.31268355e-01, -2.99775970e-01,  1.06936112e+00,
       -5.76414438e-01, -6.83648627e-01,  1.97779309e+00, -6.38531339e-01,
        1.36433511e+00, -1.93765698e-01, -1.02740161e+00, -1.01895876e+00,
        1.26075413e-01, -3.90300773e-02,  9.29847356e-02, -2.06002774e-01,
       -4.15210608e-01, -

## 9.3. Norms

In [4]:
frobenius = np.linalg.norm(A)
infinite = np.linalg.norm(A,np.inf)
U,S,V = np.linalg.svd(B)
sv = U@ np.diag(S)@V-B
frobenius, infinite, np.amax(sv), np.amin(sv)

(315.32819824859763,
 434.37556837669865,
 2.1961599205866378e-14,
 -3.5416114485542494e-14)

## 9.4. Power iteration

In [5]:
from time import process_time
Z= np.random.normal(0, 1, (n, n))
start= process_time()
evalue, evector = np.linalg.eig(Z)
maxval= np.amax(evalue)
end= process_time()
print("max eigenvalue: ", maxval)
print("eigenvector: ", evector)
print("time: ", end-start)

max eigenvalue:  (14.234417107134394+0.6036367701789791j)
eigenvector:  [[ 3.35718550e-04-1.79827263e-02j  3.35718550e-04+1.79827263e-02j
  -8.94647720e-02+4.88304088e-02j ...  6.78130339e-02-3.57004025e-02j
   1.09308555e-01+0.00000000e+00j -3.07757602e-02+0.00000000e+00j]
 [-9.33876089e-02+1.92691140e-02j -9.33876089e-02-1.92691140e-02j
   1.24026620e-02+7.32105448e-05j ...  6.83762141e-02-7.66443045e-03j
   6.86003451e-02+0.00000000e+00j -4.59451850e-02+0.00000000e+00j]
 [ 1.32635782e-02-5.91588695e-03j  1.32635782e-02+5.91588695e-03j
  -5.84450550e-02-2.10295958e-02j ...  3.16463392e-02+1.18382792e-02j
   2.02832279e-02+0.00000000e+00j -7.43122172e-02+0.00000000e+00j]
 ...
 [-7.41110855e-02+7.55578116e-02j -7.41110855e-02-7.55578116e-02j
  -6.61286018e-02+4.96153856e-02j ... -1.01325045e-01-5.16852979e-03j
  -1.01551757e-01+0.00000000e+00j -8.76212808e-03+0.00000000e+00j]
 [-1.33690284e-05+2.79818832e-02j -1.33690284e-05-2.79818832e-02j
   5.12957075e-03-2.57351173e-02j ...  2.1236

## 9.6.  Nearest neighbor

In [6]:
def nearest_neighbor(z,A):
    x = np.abs(A - z)
    index = x.argmin()
    return A.flat[index]

print(nearest_neighbor(4,A))

4.019034049326895
